name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

        # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run TypeScript build
      - name: Build project
        run: npm run build

      # Run tests (placeholder for now)
      - name: Run tests
        run: echo "No tests yet 🚧"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy placeholder
        run: echo "✅ Deployment step goes here (Render, Railway, or Docker)"
